### ISSUE TITLE
Extracting Sprite produces an empty image, possible because of incomplete palette data

### ISSUE THREAD

**Issue by weewoo64** [ikemen-launcher/sff-extractor#1]
I've encountered a possible bug where the palette data is incomplete. For example, the palette data with group = 0 and number = 0 of Makina.sff (attached) is the following:

```
{
	index: 302,
	group: 0,
	number: 0,
	colorCount: 256,
	dataOffset: 301952,
	dataLength: 0,
	buffer: <Buffer >,
	table: []
}
```

The buffer and table are empty, which is incorrect. The attachment also includes a screenshot of the same file loaded in Fighter Factory Studio. On the right side, you can see that the table has some colors. If I extract and convert the sprite to a PNG, it produces an empty image.

Another note:
The package has been great to use so far. We only encountered a few issues extracting the sprites, but it works great most of the time. And it would be great if all the functions, like decodeSpriteBuffer, etc., were exported. 

[Archive.zip](https://github.com/user-attachments/files/16562068/Archive.zip)
<img width="1439" alt="Screenshot 2024-08-09 at 16 00 33" src="https://github.com/user-attachments/assets/b3219ec8-3ac9-4841-8a8c-f0e095498234">

**Comment by neolao** [comment]
Thanks, let me check this SFF file.

> We only encountered a few issues extracting the sprites, but it works great most of the time.

Please create an issue if you think I can improve something.

**Comment by neolao** [comment]
Ok, I think I found the rule to handle this case. I checked Fighter Factory to confirm.

When there is an empty palette, the first must be used. I tried to change a color on the palette 1, it also changes the 303.

Fixed in version 1.0.3

**Comment by weewoo64** [comment]
Thanks, and I can confirm that the 1.0.3 update fixed the bug.
And it makes sense that the first palette is the base one and can be reused like that.

I still have issues with other sprites after the update, so let me know if you are interested and if you want me to create a separate issue or use this one?

**Comment by neolao** [comment]
Can you separate issues please?
