### ISSUE TITLE
Unexpected colors when converting a Sonic sprite to PNG

### ISSUE THREAD

**Issue by weewoo64** [ikemen-launcher/sff-extractor#2]
The Sonic sprite located in group = 0 and number = 0 (Sonic.sff attached in the zip) has unexpected colors when converting to a PNG using the same convertSpriteDecodedBufferToPng function you use. I expected the same outcome portrayed in the Fight Factory software but got a different one. 

The palette data I got is:

```
{
	index: 2,
	group: 1,
	number: 1,
	colorCount: 65792,
	dataOffset: 2048,
	dataLength: 0,
	buffer: <Buffer 1e 5b 5b 00 00 00 00 ff f6 f6 f6 ff 8f 8f 9e ff ff 00 more bytes>,
	table: [
		[ 30, 91, 91, 0 ],      [ 0, 0, 0, 255 ],       [ 246, 246, 246, 255 ],
		[ 143, 143, 158, 255 ], [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 177, 228, 255, 255 ], [ 98, 202, 255, 255 ],  [ 0, 153, 230, 255 ],
		[ 0, 73, 110, 255 ],    [ 255, 242, 255, 255 ], [ 172, 149, 162, 255 ],
		[ 103, 90, 105, 255 ],  [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 23, 23, 255 ],
		[ 164, 13, 13, 255 ],   [ 85, 7, 7, 255 ],      [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 111, 54, 251, 255 ],  [ 59, 26, 139, 255 ],   [ 27, 7, 76, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 221, 214, 163, 255 ], [ 10, 148, 0, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 249, 216, 200, 255 ],
		[ 235, 153, 115, 255 ], [ 165, 85, 45, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],   [ 255, 0, 255, 255 ],
		[ 75, 77, 99, 255 ],    [ 31, 31, 40, 255 ],    [ 255, 0, 255, 255 ],
		[ 255, 0, 255, 255 ],
		... more items
	]
}
```

The table data does seem to have the same values as in Fighter Factory, so I am unsure why the end result is different.

----------------------------------------

Both examples are also attached to the issue.
Before the 1.0.3 update it produced an empty image.

[Sonic.zip](https://github.com/user-attachments/files/16570236/Sonic.zip)
<img width="1440" alt="Fighter-Factory-Sonic" src="https://github.com/user-attachments/assets/0667305b-5d41-4b82-b178-6658a8a57078">
![Sonic](https://github.com/user-attachments/assets/cce7d939-350d-4feb-a78b-15184686267d)

**Comment by neolao** [comment]
Hmmm ok 🤔, picking the first palette when the palette is empty is not right here.

The previous palette looks ok. I have to guess a logic. Thanks to you, I created a unit test for your previous issue. And I will create another one for Sonic 😅

**Comment by weewoo64** [comment]
Hmmm, it sounds like there is different logic between different characters, always tricky.
I have the same issue finding the correct sprite location. While there are some standards, finding the location of the whole body of the in-game character is quite different for some of the characters.

I've included two extra samples that show the difference between Fight Factory and converting the sprite to a PNG. I am not sure if that is the same issue as Sonic, but it might be helpful. With these two examples, if I apply an external palette file associated with the sprite, it does render correctly. But I don't think that happens in Fighter Factory..

And if the logic is random between characters, I don't think you can really fix this issue.

---------------

<img width="1434" alt="Fighter-Factory-Gray" src="https://github.com/user-attachments/assets/bae087fc-6092-4a79-af25-b1f5b98f5e91">

![Gray_Start](https://github.com/user-attachments/assets/39b670b9-42d2-42b4-8c1e-72a20a8f5ad0)

[Gray_Start[0,0].sff.zip](https://github.com/user-attachments/files/16570621/Gray_Start.0.0.sff.zip)

---------------

<img width="1440" alt="Fighter-Factory-Lucilfer" src="https://github.com/user-attachments/assets/953d20f7-841e-4365-87b4-acd1ed60bc6f">

![Lucilfer](https://github.com/user-attachments/assets/6c9816db-8cf1-4f61-881f-dfecfba9135d)

[Lucilfer[0,0].sff.zip](https://github.com/user-attachments/files/16570624/Lucilfer.0.0.sff.zip)

**Comment by neolao** [comment]
It's not random.

I can also try to understand the source code of IkemenGo, it's not easy (weird variable names, functions and logic).

Thanks for the files, I will try to figure it out.

**Comment by neolao** [comment]
note: Gray and Lucifer files are v1 SFF, it's another fix

**Comment by neolao** [comment]
Can you try the version 1.0.4?

For Gray and Lucifer, I will create another version

**Comment by weewoo64** [comment]
Version 1.0.4 did not fix Gray and Lucifer for me.

This is how I use the library:
```
const buffer = readFileSync(path.join(__dirname, `../../test/_chars/Lucilfer.sff`))
const { sprites } = extract(buffer, {
	palettes: true,
	paletteTable: true,
	paletteBuffer: true,
	spriteBuffer: false,
	decodeSpriteBuffer: true,
})
```

**Comment by neolao** [comment]
Yes I know. I will create another version

**Comment by neolao** [comment]
Can you try the version 1.0.5?

**Comment by weewoo64** [comment]
Can confirm that 1.0.5 fixes all three characters!
