### ISSUE TITLE
Incorrect colors when converting PiccoloInSeph sprite to PNG

### ISSUE THREAD

**Issue by weewoo64** [ikemen-launcher/sff-extractor#3]
The PiccoloInSeph sprite located in group = 0 and number = 0 (PiccoloInSeph.sff attached in the zip) has incorrect colors when converted to a PNG using the same convertSpriteDecodedBufferToPng function you use. I expected the same outcome portrayed in the Fight Factory software but got a different one.

[PiccoloInSeph.sff.zip](https://github.com/user-attachments/files/16598610/PiccoloInSeph.sff.zip)

<img width="1440" alt="Screenshot 2024-08-13 at 13 18 42" src="https://github.com/user-attachments/assets/1cb248ba-4696-4577-9386-68a24145efbc">

![0-0](https://github.com/user-attachments/assets/3be6fe93-745b-4f66-b8de-1c4bffe0272f)

![9000-0](https://github.com/user-attachments/assets/5d0df1a2-058a-42ab-8b20-1ba30e797dd5)

**Comment by neolao** [comment]
Can you try the version 1.0.6?

**Comment by weewoo64** [comment]
Confirm it fixed the issue, thanks!
