### ISSUE TITLE
Missing colors when converting Kumagawa sprite to PNG

### ISSUE THREAD

**Issue by weewoo64** [ikemen-launcher/sff-extractor#4]
When converted to a PNG using the same convertSpriteDecodedBufferToPng function you use, the Kumagawa sprite located in group = 9000 and number = 1 (Kumagawa.sff.zip attached) has missing colors, mainly in the collar and teeth.

[Kumagawa.sff.zip](https://github.com/user-attachments/files/16604640/Kumagawa.sff.zip)

<img width="1440" alt="Screenshot 2024-08-13 at 21 55 57" src="https://github.com/user-attachments/assets/bb13acd2-b3f5-4b59-9520-65be2b56ef01">

![bitmap-lg](https://github.com/user-attachments/assets/03f51b14-2489-4e6b-accf-844f468f8d7f)

**Comment by neolao** [comment]
Not an easy issue, I have to change how I decode PNG8.

To explain the bug, I currently consider a pixel transparent if the RGB components are the same as the first in the palette.
It's a bad implementation because in this image, there is another white (255, 255, 255) but not transparent.

**Comment by neolao** [comment]
Can you try the version 1.0.7?

**Comment by weewoo64** [comment]
Version 1.0.7 fixes the image, many thanks once again!
