### ISSUE TITLE
Extracting Kazuki Sprite with decodeSpriteBuffer = true results in an error

### ISSUE THREAD

**Issue by weewoo64** [ikemen-launcher/sff-extractor#5]
If I extract [Kazuki.sff](https://drive.google.com/file/d/1l4gWJ5sYdA8etxcDNBWqUP02agDIJK7g/view?usp=sharing) with decodeSpriteBuffer = true option, I get the following error:

```
Error: PLTE not found
```

<img width="1440" alt="Screenshot 2024-08-14 at 19 28 11" src="https://github.com/user-attachments/assets/09a51879-5049-4806-8417-fa0cd7a57a43">

**Comment by neolao** [comment]
thanks, it's the first time I see this setting set to true
<img width="251" alt="Capture d’écran 2024-08-14 à 22 33 29" src="https://github.com/user-attachments/assets/53f50ca7-7797-452c-8f01-60e1d6404017">

**Comment by neolao** [comment]
Can you try the version 1.0.8?

I also improved the error message. If the decode fails, the message will contain the sprite group+number.

**Comment by weewoo64** [comment]
Good find; I didn't see that one in FF.
And I can confirm that version 1.0.8 fixes the issue.
